# Generated by Django 3.2.20 on 2023-10-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Сырье')),
                ('iron_con', models.FloatField(verbose_name='Содержание железа')),
                ('silicon_con', models.FloatField(verbose_name='Содержания кремния')),
                ('aluminum_con', models.FloatField(verbose_name='Содержание алюминия')),
                ('calcuim_con', models.FloatField(verbose_name='Содержание кальция')),
                ('sulfure_con', models.FloatField(verbose_name='Содержание серы')),
                ('month', models.CharField(choices=[('январь', 'январь'), ('февраль', 'январь'), ('март', 'январь'), ('апрель', 'январь'), ('май', 'январь'), ('июнь', 'январь'), ('июль', 'январь'), ('август', 'январь'), ('сентябрь', 'январь'), ('октябрь', 'январь'), ('ноябрь', 'январь'), ('декабрь', 'январь')], max_length=10, verbose_name='Месяц')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('январь', 'январь'), ('февраль', 'январь'), ('март', 'январь'), ('апрель', 'январь'), ('май', 'январь'), ('июнь', 'январь'), ('июль', 'январь'), ('август', 'январь'), ('сентябрь', 'январь'), ('октябрь', 'январь'), ('ноябрь', 'январь'), ('декабрь', 'январь')], max_length=10, verbose_name='Месяц')),
                ('raws', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report', to='stats.rawmodel', verbose_name='Отчет')),
            ],
        ),
    ]
