# Generated by Django 3.2.20 on 2023-10-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmodel',
            old_name='calcuim_con',
            new_name='calcium_con',
        ),
    ]
