# Generated by Django 3.2.20 on 2023-10-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_calcuim_con_rawmodel_calcium_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='raws',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report', to='stats.rawmodel', verbose_name='Отчет'),
        ),
    ]
