# Generated by Django 3.2.20 on 2023-10-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_alter_reportmodel_raws'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmodel',
            name='raws',
        ),
    ]
