# Generated by Django 3.2.20 on 2023-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_reportmodel_raws'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='raws',
            field=models.ManyToManyField(to='stats.RawModel', verbose_name='Сырье'),
        ),
    ]
