# Generated by Django 3.2.20 on 2023-10-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_rawmodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportModel',
        ),
    ]
